### ISSUE TITLE
5t89: Assembly clustering problem

### ISSUE THREAD

**Issue by sbliven** [eppic-team/eppic#175]
Many of the 5T89 assemblies seem to be duplicated. For instance, Assembly 7 (1,5-8) and Assembly 8 (3,5-8) generate the same A2B2 assembly. They should really be unified as (1,3,5-8).

**Comment by lafita** [comment]
Can this be a problem with the heteromeric graph contraction? It seems that including interfaces 5-8 implies that interfaces 1 and 3 should also be in the assembly. We need to create a test for that.

**Comment by josemduarte** [comment]
There's no graph contraction happening for this entry, so it is some sort of clustering issue. [You can check if it graph contraction applies by checking that field `exhaustiveAssemblyEnumeration` is `false` in table `PdbInfo`]

**Comment by josemduarte** [comment]
In terms of interface clusters the assemblies that don't cluster are {1,5,6} and {3,5,6}. That's because the {1,3,5,6} assembly is not in the list of valid assemblies, if it was then all of them would cluster correctly. 

Assembly {1,3,5,6} seems to be missing because its parent {1,3} is detected as invalid when it should be valid.
