### ISSUE TITLE
MySQL database collation bug

### ISSUE THREAD

**Issue by kumar-physics** [eppic-team/eppic#36]
The collation scheme is not same for all tables in the database. 
In SeqCluster table pdbCode and repChain are in 'latin1_general_cs', while the rest of the tables having 'latin1_swedish_ci'. 

Its better to use case sensitive character set for all tables, otherwise one need to use 'binary' flag in comparing strings.

**Comment by josemduarte** [comment]
The bug happens because of a specific fix we introduced for the sequence clusters URL queries to work properly for entries with both upper and lower case chains. See issue in legacy project eppic-wui: https://github.com/eppic-team/eppic-wui/issues/4 (enable issues in the eppic-wui project to be able to see it). 

The commit aboves removes that setting, but it is important to set the default database collation to case sensitive for everything to work, i.e. the `my.cnf` file must have this:
```
character-set-server=latin1
collation-server=latin1_general_cs
```

**Comment by josemduarte** [comment]
Use this kind of query for finding out collations for whole db (thanks @kumar-physics) :
```sql
SELECT table_schema, table_name, column_name, character_set_name, collation_name 
FROM information_schema.columns 
WHERE collation_name = 'latin1_general_cs' 
ORDER BY table_schema, table_name,ordinal_position;
```

**Comment by josemduarte** [comment]
This has been fixed with the patch above. Though it does depend on setting the right collation a the database config level. It would be good to find a more robust solution at some point. For the moment we can live with it, I'll move it to 3.1.
