### ISSUE TITLE
Displaying PDB assembly predictions, EPPIC disjoint assemblies and invalid assemblies

### ISSUE THREAD

**Issue by gcapitani** [eppic-team/eppic#54]
In order to clearly display PDB assembly predictions it seems that an additional column in the assembly panel would be a good solution to tag the EPPIC assembly that corresponds to the PDB prediction. 
A special case occurs when the PDB prediction is an invalid assembly, in that case EPPIC will output that assembly as the last row and it is important to clearly show users that it is invalid. A simple way is to use the thumbnail field, which is anyway empty in those cases. There one could display a .png with the text "TOPOLOGICALLY INVALID".
The same approach could be employed to clearly tag disjoint assemblies: see e.g. the case of 1jap, where currently the same cartoon icon corresponds to both A,I and AI stoichiometries. An assembly like A,I should not have a graphical representation, but just a "DISJOINT ASSEMBLY" text in the thumbnail field.

**Comment by sbliven** [comment]
If we add a schematic thumbnail, that would make it clear which chains are interacting.

Alternately, what if we translate the subassemblies so that there is a visible gap between them? This could be either done by choosing a different lattice point (consistent with 3D), or just by composing multiple images for the thumbnail.

**Comment by josemduarte** [comment]
This is several issues in one,  I've now split it into its subcomponents: #100 #101 #102
