### ISSUE TITLE
More relations between db tables

### ISSUE THREAD

**Issue by sbliven** [eppic-team/eppic#87]
I found myself performing some awkward joins and wondered if adding the following relations to the database would make sense.
1. Reference between Interface and ChainCluster, e.g. Interface.chainCluster1_uid and Interface.chainCluster2_uid. The only current way to get the two clusters for a particular interface is to look through all clusters for that PDB and match Interface.chain1/2 to the comma-separated list ChainCluster.memberChains.
2. Reference between Contact and ResidueInfo, e.g. Contact.firstResidueInfo_uid and Contact.secondResidueInfo_uid. (Aside: this is the only table that spells out first/second in the member names. All other tables use numbers, e.g. resNumber1/2.)  This would make it easier to get entropy properties.

Are there any issues with performance or hibernate that would prevent this from being a good idea?

**Comment by josemduarte** [comment]
I agree we should have the relations. I've also stumbled across that problem before and found it very difficult to link between the tables. In any case, when using java code through jpa/hibernate this is not such a big problem, because you basically deserialize all tables into java objects and then it's quite easy (and fast) to get what you want from the objects.

Anyway, in order to add the relations we would need to do it at the jpa/hibernate level via modifying orm.xml and possibly also by adding the cross references in the java classes.

**Comment by sbliven** [comment]
That sounds daunting. I'll have to look for a good tutorial on hibernate. Or maybe @altheaparker has the necessary expertise?

**Comment by sbliven** [comment]
Note that if #88 is implemented, Interface should reference the new Chain table rather than ChainCluster

**Comment by sbliven** [comment]
Given that the current system works, I'm ruthlessly closing this.

BTW, this is connected to #88.
